### PR TITLE
added support to pass arguments to the PowerShell script

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by icnocop** [comment]
What do you recommend is the best way to test these changes?

**Comment by pgroene** [comment]
It depends on the change. In this case you have changed the json, I would make a new version and upload it to my account with tfx to test it. When I have changes in the ps file, I test it with a local host (do the change in the local dir and then test a new build, the ps file used is not overridden till you upload a new version). When changing the manifest. I upload a test vsix (private) to the marketplace and deploy it in my account.

I was wondering what arguments you would like to pass to the script engine? Because I'm not sure how to test this. When looking at the MS task I guess we are missing something in the script it self?

I shall fix the typo in the sample code.

**Comment by icnocop** [comment]
Thank you.

i would like to pass in built-in variables such as $(Build.BuildNumber) and also custom build variables, which may also be marked as secret.
Ex. "-buildNumber $(Build.BuildNumber) -secretPassword $(SecretPassword)"

The powershell script would support these arguments as parameters.
Ex. "Param(
[string]$buildNumber,
[string]$secretPassword)"

The built-in VSTS Powershell script already supports this.
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/powerShell/task.json

Thank you.

**Comment by pgroene** [comment]
Good reason, but I think we have to change the scripts like the new Azure PowerShell version https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzurePowerShell/AzurePowerShell.ps1. The powershell version works because it executes the script directly. In the inline powershell task the script is in a variable. When I have time, I'll look into the details.

**Comment by pgroene** [comment]
What is your account vsts account name? I'll try to make a test version of the change to test if the arguments are working and then share it with your account.

**Comment by pgroene** [comment]
I'm testing the code, however if you execute on a local agent it does not yet support the powershell3 target. This means I need to make 2 powershell scripts in the tasks. I believe in the classic powershell or azure powershell target you can still access the secure variables.

**Comment by jessehouwing** [comment]
Correct. On ps3 the secure variable must be passed to the task in the Ui
for it to be able to access it.

**Comment by pgroene** [comment]
I have it working for the powershell3 task, now working on the backwards compatibility of the local agent. That one will not support the arguments because it already can access the parameters.

**Comment by pgroene** [comment]
Added support for arguments, and powershell3

https://pgroene.wordpress.com/2016/05/20/using-the-inline-powershell-vsts-task/

**Pull request closed without merging**
